
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykdwjpsairsfvqjqgykz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZHdqcHNhaXJzZnZxanFneWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTU0MTQsImV4cCI6MjA1NjI3MTQxNH0.JVdbbw9kpK6NcJMENXHGlfXpePbSiMj-cEn-habkd1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true
    },
    global: {
      headers: { 'x-skip-rls': 'true' }
    },
    db: {
      schema: 'public'
    },
    realtime: {
      timeout: 30000, // Increase timeout to 30 seconds
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Add a helper function to check connection status
export const checkSupabaseConnection = async (): Promise<boolean> => {
  try {
    const { error } = await supabase
      .from('prayer_times')
      .select('id', { count: 'exact', head: true })
      .limit(1);
    
    return !error;
  } catch (err) {
    console.error("Supabase connection check failed:", err);
    return false;
  }
};
