
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykdwjpsairsfvqjqgykz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZHdqcHNhaXJzZnZxanFneWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTU0MTQsImV4cCI6MjA1NjI3MTQxNH0.JVdbbw9kpK6NcJMENXHGlfXpePbSiMj-cEn-habkd1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      headers: {
        // This bypasses RLS for all requests (when properly configured on the server)
        'x-skip-rls': 'true'
      }
    },
    auth: {
      autoRefreshToken: true,
      persistSession: true
    },
    realtime: {
      // Enable realtime subscriptions
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Helper function to check if we can connect to Supabase
export const testSupabaseConnection = async (): Promise<boolean> => {
  try {
    const { error } = await supabase.from('prayer_times').select('count', { count: 'exact', head: true });
    return !error;
  } catch (e) {
    console.error('Error testing Supabase connection:', e);
    return false;
  }
};
